# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 24.8.0 # Используем ту же версию, что и в pyproject.toml
    hooks:
    -   id: black

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5 # Используем ту же версию, что и в pyproject.toml
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
